<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="HRMV1" duration-ms="104830" started-at="2019-11-18T03:58:27Z" finished-at="2019-11-18T04:00:12Z">
    <groups>
    </groups>
    <test name="HRMTest" duration-ms="104830" started-at="2019-11-18T03:58:27Z" finished-at="2019-11-18T04:00:12Z">
      <class name="com.HRM.TestCases.TC_Add_Employee_003">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.HRM.TestCases.TC_Add_Employee_003@183967b]" name="setup" is-config="true" duration-ms="11339" started-at="2019-11-18T03:59:47Z" finished-at="2019-11-18T03:59:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="TC_003_AddNewEmployee()[pri:0, instance:com.HRM.TestCases.TC_Add_Employee_003@183967b]" name="TC_003_AddNewEmployee" duration-ms="11971" started-at="2019-11-18T03:59:58Z" finished-at="2019-11-18T04:00:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.HRM.TestCases.TC_Add_Employee_003.TC_003_AddNewEmployee(TC_Add_Employee_003.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_AddNewEmployee -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.HRM.TestCases.TC_Add_Employee_003@183967b]" name="TearDown" is-config="true" duration-ms="2107" started-at="2019-11-18T04:00:10Z" finished-at="2019-11-18T04:00:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.HRM.TestCases.TC_Add_Employee_003 -->
      <class name="com.HRM.TestCases.TC_Login_DDT_002">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.HRM.TestCases.TC_Login_DDT_002@1e3c938]" name="setup" is-config="true" duration-ms="13679" started-at="2019-11-18T03:58:58Z" finished-at="2019-11-18T03:59:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="TC_002_Login_DDT(java.lang.String, java.lang.String)[pri:0, instance:com.HRM.TestCases.TC_Login_DDT_002@1e3c938]" name="TC_002_Login_DDT" duration-ms="9216" started-at="2019-11-18T03:59:17Z" data-provider="Data_Sheet" finished-at="2019-11-18T03:59:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_Login_DDT -->
        <test-method status="FAIL" signature="TC_002_Login_DDT(java.lang.String, java.lang.String)[pri:0, instance:com.HRM.TestCases.TC_Login_DDT_002@1e3c938]" name="TC_002_Login_DDT" duration-ms="3805" started-at="2019-11-18T03:59:26Z" data-provider="Data_Sheet" finished-at="2019-11-18T03:59:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.HRM.TestCases.TC_Login_DDT_002.TC_002_Login_DDT(TC_Login_DDT_002.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_Login_DDT -->
        <test-method status="PASS" signature="TC_002_Login_DDT(java.lang.String, java.lang.String)[pri:0, instance:com.HRM.TestCases.TC_Login_DDT_002@1e3c938]" name="TC_002_Login_DDT" duration-ms="6628" started-at="2019-11-18T03:59:30Z" data-provider="Data_Sheet" finished-at="2019-11-18T03:59:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_Login_DDT -->
        <test-method status="PASS" signature="TC_002_Login_DDT(java.lang.String, java.lang.String)[pri:0, instance:com.HRM.TestCases.TC_Login_DDT_002@1e3c938]" name="TC_002_Login_DDT" duration-ms="5265" started-at="2019-11-18T03:59:36Z" data-provider="Data_Sheet" finished-at="2019-11-18T03:59:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_Login_DDT -->
        <test-method status="FAIL" signature="TC_002_Login_DDT(java.lang.String, java.lang.String)[pri:0, instance:com.HRM.TestCases.TC_Login_DDT_002@1e3c938]" name="TC_002_Login_DDT" duration-ms="3326" started-at="2019-11-18T03:59:42Z" data-provider="Data_Sheet" finished-at="2019-11-18T03:59:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.HRM.TestCases.TC_Login_DDT_002.TC_002_Login_DDT(TC_Login_DDT_002.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_Login_DDT -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.HRM.TestCases.TC_Login_DDT_002@1e3c938]" name="TearDown" is-config="true" duration-ms="1674" started-at="2019-11-18T03:59:45Z" finished-at="2019-11-18T03:59:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.HRM.TestCases.TC_Login_DDT_002 -->
      <class name="com.HRM.TestCases.TC_Login_Test_001">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.HRM.TestCases.TC_Login_Test_001@c0a365]" name="setup" is-config="true" duration-ms="18454" started-at="2019-11-18T03:58:29Z" finished-at="2019-11-18T03:58:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="TC_001_Login_Test()[pri:0, instance:com.HRM.TestCases.TC_Login_Test_001@c0a365]" name="TC_001_Login_Test" duration-ms="6608" started-at="2019-11-18T03:58:47Z" finished-at="2019-11-18T03:58:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_Login_Test -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.HRM.TestCases.TC_Login_Test_001@c0a365]" name="TearDown" is-config="true" duration-ms="3839" started-at="2019-11-18T03:58:54Z" finished-at="2019-11-18T03:58:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.HRM.TestCases.TC_Login_Test_001 -->
    </test> <!-- HRMTest -->
  </suite> <!-- HRMV1 -->
</testng-results>
